info:
  build-date: '@project.build.date@'
  build-version: '@project.build.version@'

server:
  port: ${port:8081}
  contextPath: /calc
  tomcat:
    max-threads: 100
    min-spare-threads: 10

management:
  context-path: '/actuator'
  security:
    enabled: false
  info:
    build:
      enabled: true

endpoints: 
  jmx:
    domain: spring-boot-calc
    unique-names: true

spring:
  profiles:
    active: '@profiles.active@'
  application:
    name: spring-boot-calc
  jmx:
    default-domain: spring-boot-calc
  boot:
    admin:
      url: http://${boot.admin.url:localhost}:${boot.admin.port:8080}/admin
  devtools:
    livereload:
      enabled: false
  output:
    ansi:
      enabled: DETECT
  session:
    store-type: redis
  redis:
    database: 1
    host: ${redis.host:192.168.8.200}
    port: ${redis.port:6379}
    password: ${redis.password:''}
    timeout: 5000
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
  rabbitmq:
    host: ${rabbitmq.host:192.168.8.200}
    port: ${rabbitmq.port:5672}
    username: ${rabbitmq.username:admin}
    password: ${rabbitmq.password:admin}
    virtual-host: ${rabbitmq.vhost:/}
  zookeeper:
    enabled: true
    connectAddress: ${zookeeper.address:192.168.8.200:2181}
    sessionTimeout: 30000
    connectionTimeout: 30000
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${mysql.host:192.168.8.200}:${mysql.port:3306}/${mysql.database:test}
    username: ${mysql.username:test}
    password: ${mysql.password:test}
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,log4j,log4j2
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  messages:
    basename: i18n/messages,i18n/resource/messages,i18n/system/messages
    cache-seconds: 3600
    encoding: UTF-8
    
mybatis:
  mapper-locations:
    - classpath:com/catvgd/springbootdemo/common/*/mapper/*Mapper.xml
    - classpath:com/catvgd/springbootdemo/biz/*/mapper/*Mapper.xml
  type-aliases-package: com.catvgd.springbootdemo.common.*.model,com.catvgd.springbootdemo.biz.*.model
mapper:
  mappers:
    - com.catvgd.springbootdemo.common.tkmapper.util.MyMapper
  not-empty: false
  identity: MYSQL
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
