
INSERT INTO SYS_ACCOUNT (ACCOUNT, PASSWORD, USER_ID)
VALUES ("zs", "123", "1");


INSERT INTO SYS_USER (UID, USERNAME, PASSWARD, EMAIL)
VALUES (1, "张三1", "abc", "abc@qq.com");
INSERT INTO SYS_USER (UID, USERNAME, PASSWARD, EMAIL)
VALUES (2, "张三1", "abc", "abc@qq.com");
INSERT INTO SYS_USER (UID, USERNAME, PASSWARD, EMAIL)
VALUES (3, "张三3", "abc", "abc@qq.com");

INSERT INTO SYS_ROLE (RID, ROLE_NAME, ROLE_TYPE)
VALUES (1, "rw", "rw");

INSERT INTO SYS_PERMISSION (PID, PERM_URL, PERM_DESC)
VALUES (1, "abc", "abc");

INSERT INTO SYS_USER_ROLE (UID, RID)
VALUES (1, 1);

INSERT INTO SYS_ROLE_PERMISSION (RID, PID)
VALUES (1, 1);
