
INSERT INTO SYS_USER (USER_ID, USER_NAME, REAL_NAME, REMARK)
VALUES (1, "张三1", "张三", "测试");
INSERT INTO SYS_USER (USER_ID, USER_NAME, REAL_NAME, REMARK)
VALUES (2, "张三1", "张三", "测试");
INSERT INTO SYS_USER (USER_ID, USER_NAME, REAL_NAME, REMARK)
VALUES (3, "张三3", "张三", "测试");

INSERT INTO SYS_ACCOUNT (ACCOUNT, PASSWORD, USER_ID)
VALUES ("zs", "123", "1");
